### ISSUE TITLE
Move to rust 

### ISSUE THREAD

**Issue by X-x-X-x-X-x-X-x-X-x-X-x-X-x-X-x-X** [X-x-X-x-X-x-X-x-X-x-X-x-X-x-X-x-X/bootloader#2]

**Comment by Sxmourai** [comment]
Nearly done =)

**Comment by X-x-X-x-X-x-X-x-X-x-X-x-X-x-X-x-X** [comment]
I've actually removed the need for having an assembly file and did everything through inline assembly files in the bootstrapper :3 

Thank you to Brightshard for examples (from your own bootstrap code) and for the chats helping me.

**Comment by Sxmourai** [comment]
Are you sure you commited tho ?

**Comment by X-x-X-x-X-x-X-x-X-x-X-x-X-x-X-x-X** [comment]
Working on it!!!!!
